# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-27 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1200)),
                ('travel_start', models.DateField()),
                ('travel_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('going_on', models.ManyToManyField(to='belt.User')),
            ],
        ),
    ]
